# configuration of workflow
workdir: 'output/'
adata: 'data/adata.h5ad'

# key and groups to use for catagorical variables 
# put empty list [] if selecting all groups 
gene:
  key: 'ensg'

phenotype: 
  key: 'cell_groups'
  groups: ['Tcell', 'Monocytes', 'DC']

# if single sample, set key=''
sample:
  key: 'patient'
  groups: []

cellphonedb:
  args:
    iterations: 1000
    threshold: 0.1
    threads: 4